SensorDeEventos/SensorDeEventos.Web/Models/Dto/EventoDto.cs
using SensorDeEventos.Web.Models.ViewModel;
using System;
using System.Text.Json.Serialization;

namespace SensorDeEventos.Web.Models.Dto
{
    public class EventoDto
    {
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        [JsonPropertyName("tag")]
        public string Tag { get; set; }

        [JsonPropertyName("valor")]
        public string Valor { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("dataEHora")]
        public DateTime DataEHora { get; set; }

        public static implicit operator EventoViewModel(EventoDto evento)
        {

            return new EventoViewModel
            {
                Id = evento.Id,
                Pais = evento.Tag.Split(".")[0],
                Regiao = evento.Tag.Split(".")[1],
                Sensor = evento.Tag.Split(".")[2],
                DataDeEntrada = evento.DataEHora.ToString("d"),
                HorarioDeEntrada = evento.DataEHora.ToString("t"),
                Status = evento.Status,
                Valor = ConverterValorParaInteiro(evento.Valor)
            };
        }

        private static int ConverterValorParaInteiro(string valor)
        {
            return !string.IsNullOrWhiteSpace(valor) ? Convert.ToInt32(valor) : 0;
        }
    }
}

SensorDeEventos/SensorDeEventos.Web/Models/ErrorViewModel.cs
using System;

namespace SensorDeEventos.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SensorDeEventos/SensorDeEventos.Web/Models/GerarGrafico.cs
using SensorDeEventos.Web.Models.ViewModel;
using SensorDeEventos.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensorDeEventos.Web.Models
{
    public class GerarGrafico
    {
        private readonly SensorDeEventosServices sensorDeEventosServices;

        public GerarGrafico(SensorDeEventosServices sensorDeEventosServices)
        {
            this.sensorDeEventosServices = sensorDeEventosServices;
        }

        public async Task<object> PorRegiao()
        {
            var eventos = await sensorDeEventosServices.GetAll();
            eventos.ForEach(x => x.ConcatenarRegiao());
            return AgruparDadosPor(x => x.Regiao, eventos);
        }

        public async Task<object> PorSensor()
        {
            var eventos = await sensorDeEventosServices.GetAll();
            eventos.ForEach(x => x.ConcatenarSensor());
            return AgruparDadosPor(x => x.Sensor, eventos);
        }

        private object AgruparDadosPor(Func<EventoViewModel, string> group, List<EventoViewModel> eventos)
        {
            var resultado = eventos.Where(x => x.Valor > 0)
                .GroupBy(group)
                .Select(x => new
                {
                    name = x.Key,
                    y = x.Sum(y => y.Valor)
                }).ToList();


            return resultado;
        }

    }
}

SensorDeEventos/SensorDeEventos.Web/Models/ViewModel/EventoViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SensorDeEventos.Web.Models.ViewModel
{
    public class EventoViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "País")]
        public string Pais { get; set; }


        [Display(Name = "Região")]
        public string Regiao { get; set; }

        [Display(Name = "Sensor")]
        public string Sensor { get; set; }

        [Display(Name = "Valor")]
        public int Valor { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "Data de entrada")]
        public string DataDeEntrada { get; set; }

        [Display(Name = "Horário de entrada")]
        public string HorarioDeEntrada { get; set; }

        public void ConcatenarRegiao()
        {
            Regiao = $"{Pais}.{Regiao}";
        }

        public void ConcatenarSensor()
        {
            Sensor = $"{Pais}.{Regiao}.{Sensor}";
        }
    }
}

SensorDeEventos/SensorDeEventos.Web/Controllers/GraficoController.cs
using Microsoft.AspNetCore.Mvc;
using SensorDeEventos.Web.Models;
using System.Threading.Tasks;

namespace SensorDeEventos.Web.Controllers
{
    public class GraficoController : Controller
    {
        public async Task<IActionResult> GerarGraficoPorRegiao([FromServices] GerarGrafico gerarGrafico)
        {
            var resultado = await gerarGrafico.PorRegiao();

            return Json(resultado);
        }
        public async Task<IActionResult> GerarGraficoPorSensor([FromServices] GerarGrafico gerarGrafico)
        {
            var resultado = await gerarGrafico.PorSensor();

            return Json(resultado);
        }
    }
}

SensorDeEventos/SensorDeEventos.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SensorDeEventos.Web.Models;
using SensorDeEventos.Web.Services;
using System.Diagnostics;
using System.Threading.Tasks;

namespace SensorDeEventos.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Eventos([FromServices] SensorDeEventosServices services)
        {
            var eventos = await services.GetAll();

            return View(eventos);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SensorDeEventos/SensorDeEventos.Web/Views/Home/Eventos.cshtml
@model IEnumerable<SensorDeEventos.Web.Models.ViewModel.EventoViewModel>

@{
    ViewData["Title"] = "Eventos";
}

<div class="row">
    <div class="col-md-12">
        <h4>
            @ViewData["Title"]
        </h4>
    </div>

    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead class="thead-dark">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Pais)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Regiao)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Sensor)
                                </th>
                                <th class="text-center">
                                    @Html.DisplayNameFor(model => model.Valor)
                                </th>
                                <th class="text-center">
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th class="text-center">
                                    @Html.DisplayNameFor(model => model.DataDeEntrada)
                                </th>
                                <th class="text-center">
                                    @Html.DisplayNameFor(model => model.HorarioDeEntrada)
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Any())
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Pais)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Regiao)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Sensor)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.Valor)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.Status)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.DataDeEntrada)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.HorarioDeEntrada)
                                        </td>
                                    </tr>
                                }



                            }
                            else
                            {

                                <tr>
                                    <td colspan="7">Você ainda não possui nenhum registro de evento.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

SensorDeEventos/SensorDeEventos.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-6">
                <button type="button" class="btn btn-outline-primary btn-block" onclick="getGraficoPorRegiao();">
                    Gerar gráfico por região
                </button>
            </div>
            <div class="col-md-6">
                <button type="button" class="btn btn-block btn-outline-primary" onclick="getGraficoPorSensor();">
                    Gerar gráfico por sensor
                </button>
            </div>
        </div>
    </div>
    <div class="col-md-12 mt-5">
        <div id="container"></div>
    </div>
</div>


@section Scripts{
    <script src="https://code.highcharts.com/highcharts.js"></script>

    <script>
        function carregarGrafico(dados, title, nameSerie) {
            Highcharts.chart('container', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: title
                },
                accessibility: {
                    announceNewData: {
                        enabled: true
                    }
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'Total'
                    }

                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    series: {
                        borderWidth: 0,
                        dataLabels: {
                            enabled: true,
                            format: '{point.y:.1f}'
                        }
                    }
                },

                tooltip: {
                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}</b> de total<br/>'
                },

                series: [
                    {
                        name: nameSerie,
                        colorByPoint: true,
                        data: dados
                    }
                ]
            });
        }
    </script>

    <script>

         $(document).ready(() => {
             getGraficoPorRegiao();
        });

        function getGraficoPorRegiao() {
            $.get("@Url.Action("GerarGraficoPorRegiao", "Grafico")",
                function (data)
                {
                    carregarGrafico(data, "Gráfico por região", "Região");

                });
        }

        function getGraficoPorSensor() {
            $.get("@Url.Action("GerarGraficoPorSensor", "Grafico")",
                function (data)
                {
                    carregarGrafico(data, "Gráfico por sensor", "Sensor");

                });
        }
    </script>
}

SensorDeEventos/SensorDeEventos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sensor de eventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sensor de eventos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Eventos">Eventos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Sensor de Eventos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>